### PR TITLE
WIP: Add setup macros to enable KAMP better integrated with Moonraker plugin manager

### PR DESCRIPTION
**Pull request by jtrmal**
This is what I have drafted. Not tested yet -- I'm on holiday leave, so I cannot test on my "production" machine.  So just sharing my progress/thoughts

### CODE REVIEW

**Comment by jtrmal** [comment]
should be able to test this or next week
y.

**Comment by jtrmal** [comment]
in ref #9

**Comment by kyleisah** [comment]
Hey dude! This all looks pretty good. You enjoy your holiday! If I get around to it I will test these out with moonraker's update manager and let you know. 

Thanks again!

**Comment by jtrmal** [comment]
Did some basic testing. 
Needs to get documented (tmrw)

**Comment by jtrmal** [comment]
this is obsoleted

**Comment by kyleisah** [comment]
❤️

**Pull request closed without merging**
