### PR TITLE
Documented to call purge macros

### PR DESCRIPTION
**Pull request by valadas**
Adding the macros to the printer.cfg was not documented

### CODE REVIEW

**Comment by kyleisah** [comment]
I don't really think this needs to be in the documentation. It's pretty self explanatory that a command will not be executed if it is not called.

**Comment by ambethia** [comment]
This is a disappointing resolution to this pull request. It's a small thing to include for someone who might overlook this detail. You might know it's a command that won't be executed, but someone else who just followed a step by step installation and enabled these features might think that the thing they just installed hooks in and adds the purge line automatically.

When I first installed this, there was no where I could see documented in this library what the macros are called that need to be added without reading the source, which shouldn't be necessary for end users.

**Comment by kyleisah** [comment]
> This is a disappointing resolution to this pull request.

Perhaps you're right. I may have been too dismissive. Let me take another look at what's been changed.

**Comment by kyleisah** [comment]
I adjusted some of the verbiage and will merge this. Sorry if I came off as dismissive. I appreciate you making an effort to contribute to the project. Thank you!

**Comment by valadas** [comment]
Excellent rewrite, thanks for merging

**Comment by ambethia** [comment]
Thank you, @kyleisah! 🥇

**Comment by Tomblarom** [comment]
This greatly helped to get started! Thanks for adding :)

**Pull request merged**
