### PR TITLE
Disable lightning speed travel for Parking

### PR DESCRIPTION
**Pull request by dct-leni**
Exmaple: As max velocity for K1c (20 000) and calculated = 600*60 = 36 000 it's bigger than max accel possible on this machine.

### CODE REVIEW

**Comment by kyleisah** [comment]
I think you’re confusing max_velocity for acceleration. 

Max_velocity is the fastest possible speed the machine can safely travel, like 300-500mm/s. The 20,000 figure you’re seeing is the *acceleration* so 20,000mm/s/s (mm/s squared). If you don’t like the rapid movement for smart parking, adjust your max_velocity value in your printer.cfg lower.

**Comment by kyleisah** [comment]
Also, the *60 you’re seeing is because we have to convert mm/s to what gcode uses, mm/m (feedrate)

**Comment by kyleisah** [comment]
600 is a pretty high velocity to use without increasing your stepper motor currents. Do a speed test and find what speed you’re comfortable with (300-500 is a common range for CoreXY) and set your velocity value to that

**Comment by MistressPlague** [comment]
My printer can easily handle 400mm/s at 65k accel. The smart park instantly stalls it. Something about it is seriously wrong. Please look back into this..

From what I can tell, it is mostly ignoring acceleration limits.

I would propose remove the curent travel_speed variable, and just above the G0 for XY movement, add this to make it dynamic:

```
    {% set current_position = printer.toolhead.position %}
    {% set current_x = current_position.x %}
    {% set current_y = current_position.y %}
    
    {% set dx = x_min - current_x %}
    {% set dy = y_min - current_y %}
    {% set distance = ((dx * dx + dy * dy) ** 0.5) | float %}

    {% set max_speed = printer.toolhead.max_velocity | float %}
    {% set min_speed = 100.0 %}

    {% set dynamic_speed = [min_speed, max_speed * (distance / 100.0)] | max %}
    {% set travel_speed = [dynamic_speed, max_speed] | min * 60.0 %}
```

**Pull request closed without merging**
