### PR TITLE
Solution to out of range error, 3 new purge modes

### PR DESCRIPTION
**Pull request by 3dimman**
This fork deals with the issue of having objects too large for KAMP to work or weird placements (out of range error due to no space for purging). With this implemented there should be no case where the error is given and a place for purging should always be found. For the case where the whole print bed is used a purge blob is printed in the middle of the object, which should be removed manually. Two new variables are added to KAMP Settings, bed_x_max and bed_y_max to set the max printable area, which is needed when purge lines are above or to the right of the object.

The macros were adjusted to work with a K1 Max so there may be some lines that are slightly different and redundant for other printers but the method for deciding the purge mode and smart park could be implemented without issue.

It is important to set the printable area dimensions before use if implemented, and to manually remove the purge blob if purge mode 5 is in effect, consider effective warnings and notices.

### CODE REVIEW

**Comment by kyleisah** [comment]
Hey there! I appreciate the PR! I do not have the time to look at this in depth right now, and I already have some stuff in the works in the development branch for the purges. I will look at these as soon as I can and see if there’s anything I like or dislike. 

At a cursory glance, I’m not a fan of defining the bed bounds manually because they can be pulled directly from the printer config as long as the machine is configured correctly. However, I will consider taking a look at what you’ve done here and see if there are some things that can possibly be added to the current purges. You will of course receive credit for those changes in the commit notes if I use them. 

Thanks again!

**Comment by 3dimman** [comment]
> Hey there! I appreciate the PR! I do not have the time to look at this in depth right now, and I already have some stuff in the works in the development branch for the purges. I will look at these as soon as I can and see if there’s anything I like or dislike.
> 
> At a cursory glance, I’m not a fan of defining the bed bounds manually because they can be pulled directly from the printer config as long as the machine is configured correctly. However, I will consider taking a look at what you’ve done here and see if there are some things that can possibly be added to the current purges. You will of course receive credit for those changes in the commit notes if I use them.
> 
> Thanks again!

You're right, I'll change it so that it pulls the dimensions directly from the PRINTER_PARAM macro. It was quicker to do testing that way and I wanted to share the rough version to see if you have general interest in it. I'll polish it up in the upcoming days and update the fork to match the default format and pull the values directly.

I'd appreciate any other feedback once you have time to look over it.

**Comment by kyleisah** [comment]
So this adds the functionality to purge without objects being defined?

**Comment by 3dimman** [comment]
Yes, if there is no object defined or you call LINE_PURGE from the console without a print it will purge along the x-axis in the centre of the bed. However, this means that if object labeling isn't enabled and KAMP is used there will be a purge line in the middle and may interfere with the object being printed.

**Comment by kyleisah** [comment]
Feel free to keep these changes for yourself, but I will not merge these as it complicates support.

**Comment by RodentVienna** [comment]
Hi Kyle, may there be an alternative approach, to this, such as disabling line_purge for a print. I am having the issue, that I want to print a model stretching over the full printplate, and there is no room for a purge line. the idea is actually great, I really hope something that solves our of range for border cases.

**Comment by 3dimman** [comment]
> Hi Kyle, may there be an alternative approach, to this, such as disabling line_purge for a print. I am having the issue, that I want to print a model stretching over the full printplate, and there is no room for a purge line. the idea is actually great, I really hope something that solves our of range for border cases.

My suggestion is to just make two start_print macros and use the macro without line purge for full plate prints, that way you won't get the error. I've also created a fork with my solution which works very well on my printer and you can use that, but I won't be keeping it up to date with the main repository

**Pull request closed without merging**
